apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jenkins-x/ext-jacoco:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jenkins-x/ext-jacoco:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: ext-jacoco
        chartPath: charts/ext-jacoco
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jenkins-x/ext-jacoco"
          image.tag: "{{.DIGEST_HEX}}"
